// screenreader-mcp adapters -- the wire package, generated from the contract.
// Copyright (C) 2026 Marlon Brandao de Sousa. GPL-2. See COPYING.txt.
//
// ROLE: adapter. This server's PRIVATE binding of specs/wire/v1/. Everything in
// it but this file is generated by tools/wiregen and committed, and the CI
// `server` job regenerates and diffs it, so the binding cannot drift from the
// published schema.
// IMPORTED BY: adapters/bridge only.
// NEVER IMPORTED BY: anything under domain/ -- enforced at review and by
// tests/architecture/imports_test.go.
//
// Why the package sits under adapters/ rather than at the server's root: it
// makes "the domain never speaks wire types" structural rather than advisory.
// The domain importing this would be a domain file importing an adapter, which
// review catches on sight.
//
// Why generated and private rather than a library shared with the bridge: spec
// 0013 decided that what is shared between implementations is the CONTRACT, not
// code -- the LSP model. Each side binds the published schema in its own
// language, on its own schedule, and interop is proven by 10c's conformance job
// rather than guaranteed by linking.
package wire

//go:generate go run ../../tools/wiregen -schema ../../../specs/wire/v1/schema.json -out wire.gen.go
