// screenreader-mcp adapters -- the wire package, generated from the contract.
// Copyright (C) 2026 Marlon Brandao de Sousa. GPL-2. See COPYING.txt.
//
// ROLE: adapter holding this server's private binding of the wire schema; everything but this file is generated by tools/wiregen.
// USED BY: adapters/bridge only, never domain/.
package wire

//go:generate go run ../../tools/wiregen -schema ../../../specs/wire/v1/schema.json -out wire.gen.go
