// Code generated by tools/wiregen from ../../../specs/wire/v1/schema.json. DO NOT EDIT.
//
// ROLE: generated adapter. The server's private binding of the published wire
// contract -- envelope types, per-command params and results, the command and
// capability constants, and the supported protocol versions. NO BEHAVIOUR
// beyond marshalling.
// IMPORTED BY: adapters/bridge only. Nothing under domain/ may import this
// package; that rule is what keeps a future wire v2 from rewriting the domain,
// and tests/architecture/imports_test.go enforces it.
//
// Regenerate with: go generate ./adapters/wire
//
// One file rather than one type per file: the one-type-per-file rule exists so
// that a human editing a type knows where it lives, and nothing here is edited
// by a human.

package wire

import "encoding/json"

// ProtocolVersion is the wire version this binding was generated from.
const ProtocolVersion = 1

// SupportedVersions is every wire version this server accepts at handshake.
//
// A set consulted by the handshake rather than a constant compared with == at
// one call site: spec 0013 leaves the hub-versus-lockstep question open and
// keeps the choice cheap, and accepting a second version must be a change to
// data, not to control flow.
//
// A function rather than a package-level var because a slice var would be
// package-level MUTABLE state, which nothing in server/ is allowed to have.
func SupportedVersions() []int {
	return []int{ProtocolVersion}
}

// Supports reports whether this server can talk to a bridge announcing version.
func Supports(version int) bool {
	for _, supported := range SupportedVersions() {
		if version == supported {
			return true
		}
	}
	return false
}

// Command is a wire command name.
type Command string

// The commands this contract defines (protocol.md §5).
const (
	CommandHello                 Command = "hello"
	CommandPing                  Command = "ping"
	CommandEcho                  Command = "echo"
	CommandPressGesture          Command = "pressGesture"
	CommandGetSpeech             Command = "getSpeech"
	CommandGetLastSpeech         Command = "getLastSpeech"
	CommandGetNextSpeechIndex    Command = "getNextSpeechIndex"
	CommandWaitForSpeech         Command = "waitForSpeech"
	CommandWaitForSpeechToFinish Command = "waitForSpeechToFinish"
	CommandGetBraille            Command = "getBraille"
	CommandGetFocusInfo          Command = "getFocusInfo"
	CommandGetState              Command = "getState"
	CommandGetConfig             Command = "getConfig"
	CommandSetConfig             Command = "setConfig"
	CommandAnnounce              Command = "announce"
	CommandBye                   Command = "bye"
)

// Capability is a closed value set in the wire contract.
type Capability string

// The values Capability may take.
const (
	CapabilitySpeech   Capability = "speech"
	CapabilityBraille  Capability = "braille"
	CapabilityGestures Capability = "gestures"
	CapabilityFocus    Capability = "focus"
	CapabilityState    Capability = "state"
	CapabilityConfig   Capability = "config"
	CapabilityAnnounce Capability = "announce"
)

// CaptureMode is a closed value set in the wire contract.
type CaptureMode string

// The values CaptureMode may take.
const (
	CaptureModeSilent CaptureMode = "silent"
	CaptureModeLive   CaptureMode = "live"
)

// LogLevel is a closed value set in the wire contract.
type LogLevel string

// The values LogLevel may take.
const (
	LogLevelDebug        LogLevel = "debug"
	LogLevelIO           LogLevel = "io"
	LogLevelDebugwarning LogLevel = "debugwarning"
	LogLevelInfo         LogLevel = "info"
)

// AckResult is the wire shape of the same name.
type AckResult struct {
	OK *bool `json:"ok,omitempty"`
}

// AnnounceParams is the wire shape of the same name.
type AnnounceParams struct {
	Text string `json:"text"`
}

// BrailleResult is the wire shape of the same name.
type BrailleResult struct {
	Text      string `json:"text"`
	FromIndex int    `json:"fromIndex"`
	ToIndex   int    `json:"toIndex"`
}

// ConfigResult is the wire shape of the same name.
type ConfigResult struct {
	Value json.RawMessage `json:"value"`
}

// EchoParams is the wire shape of the same name.
type EchoParams struct {
	Payload json.RawMessage `json:"payload"`
}

// EchoResult is the wire shape of the same name.
type EchoResult struct {
	Payload json.RawMessage `json:"payload"`
}

// ErrorInfo is the wire shape of the same name.
type ErrorInfo struct {
	Message string `json:"message"`
}

// FocusInfoResult is the wire shape of the same name.
type FocusInfoResult struct {
	Name      string   `json:"name"`
	Role      string   `json:"role"`
	States    []string `json:"states"`
	Value     *string  `json:"value"`
	AppModule *string  `json:"appModule"`
}

// GetBrailleParams is the wire shape of the same name.
type GetBrailleParams struct {
	SinceIndex int `json:"sinceIndex"`
}

// GetConfigParams is the wire shape of the same name.
type GetConfigParams struct {
	KeyPath []string `json:"keyPath"`
}

// GetSpeechParams is the wire shape of the same name.
type GetSpeechParams struct {
	SinceIndex int `json:"sinceIndex"`
}

// HelloParams is the wire shape of the same name.
type HelloParams struct {
	Mode            CaptureMode `json:"mode"`
	ProtocolVersion int         `json:"protocolVersion"`
	LogLevel        *LogLevel   `json:"logLevel,omitempty"`
}

// HelloResult is the wire shape of the same name.
type HelloResult struct {
	ProtocolVersion int          `json:"protocolVersion"`
	Reader          ReaderInfo   `json:"reader"`
	Capabilities    []Capability `json:"capabilities"`
	Mode            CaptureMode  `json:"mode"`
	Synth           string       `json:"synth"`
	LogPath         string       `json:"logPath"`
	NVDALogPath     string       `json:"nvdaLogPath"`
}

// LastSpeechResult is the wire shape of the same name.
type LastSpeechResult struct {
	Text  string `json:"text"`
	Index int    `json:"index"`
}

// NextIndexResult is the wire shape of the same name.
type NextIndexResult struct {
	Index int `json:"index"`
}

// PressGestureParams is the wire shape of the same name.
type PressGestureParams struct {
	Gestures []string `json:"gestures"`
}

// ReaderInfo is the wire shape of the same name.
type ReaderInfo struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

// Request is the wire shape of the same name.
type Request struct {
	ID     int             `json:"id"`
	Cmd    string          `json:"cmd"`
	Params json.RawMessage `json:"params,omitempty"`
}

// Response is the wire shape of the same name.
type Response struct {
	ID     int             `json:"id"`
	Result json.RawMessage `json:"result,omitempty"`
	Error  *ErrorInfo      `json:"error,omitempty"`
}

// SetConfigParams is the wire shape of the same name.
type SetConfigParams struct {
	KeyPath []string        `json:"keyPath"`
	Value   json.RawMessage `json:"value"`
}

// SpeechResult is the wire shape of the same name.
type SpeechResult struct {
	Text      string `json:"text"`
	FromIndex int    `json:"fromIndex"`
	ToIndex   int    `json:"toIndex"`
}

// StateResult is the wire shape of the same name.
type StateResult struct {
	BrowseMode *string `json:"browseMode"`
	SpeechMode string  `json:"speechMode"`
	SleepMode  bool    `json:"sleepMode"`
	InputHelp  bool    `json:"inputHelp"`
}

// WaitForSpeechParams is the wire shape of the same name.
type WaitForSpeechParams struct {
	Text       string   `json:"text"`
	AfterIndex *int     `json:"afterIndex,omitempty"`
	Timeout    *float64 `json:"timeout,omitempty"`
}

// WaitForSpeechResult is the wire shape of the same name.
type WaitForSpeechResult struct {
	Found bool   `json:"found"`
	Index int    `json:"index"`
	Text  string `json:"text"`
}

// WaitToFinishParams is the wire shape of the same name.
type WaitToFinishParams struct {
	Timeout *float64 `json:"timeout,omitempty"`
}

// WaitToFinishResult is the wire shape of the same name.
type WaitToFinishResult struct {
	Finished bool `json:"finished"`
}
